# Site settings
title: My portfolio
#description: A blog about lorem ipsum
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "http://danielfeloiola.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hello! I'm Daniel
user_description: I'm a Digital Media Researcher, and here are some of my projets. Feel free to take a look around
email: anon@anon.com
twitter_username: daniel-loiola
github_username:  danielfeloiola
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
