# Site settings
title: Meu portfólio
description: Meu portfólio pessoal
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "http://danielfeloiola.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Olá, sou o Daniel
user_description: Sou um pesquisador de mídia e comunicação digital, trabalhando especialmente com análise e visualização de dados para obter insights de plataformas e mídias sociais, e aqui estão alguns dos meus projetos. Fique a vontade.
email: danielfx19@gmail.com
twitter_username: daniel-loiola
github_username:  danielfeloiola
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-141504073-1"

exclude: ['package.json', 'src' , 'node_modules']
